plugins {
    id 'java'
    id 'application'
}

group = 'plc.simulator'
version = '0.1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'src']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
    }
}

application {
    mainClass = 'Main'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(JavaExec).configureEach {
    workingDir = projectDir
}
